### ISSUE TITLE
Variable length arrays compile error of hdf module with Visual Studio 2015

### ISSUE THREAD

**Issue by panovr** [Itseez/opencv_contrib#496] opened 2015-12-30 00:58 UTC
Variable length arrays is a C99 standard, and because Visual Studio 2015 doesn't support variable length arrays currently, so these codes will not be compiled by Visual Studio 2015, fox example, https://github.com/Itseez/opencv_contrib/blob/master/modules/hdf/src/hdf5.cpp#L329

    // fetch rank
    int n_dims = H5Sget_simple_extent_ndims( fspace );

    // fetch dims
    hsize_t dsdims[n_dims];  // error!

**Comment by cbalint13** [comment] 2016-02-17 09:39
@panovr ,

* Duplicate of https://github.com/Itseez/opencv_contrib/issues/546
* Fix is here: https://github.com/Itseez/opencv_contrib/pull/547

**Closed** 2016-02-24 10:27 UTC
Labels: bug, category: hdf
