### ISSUE TITLE
Trackers are not exposed to python

### ISSUE THREAD

**Issue by WestFlame** [Itseez/opencv_contrib#415] opened 2015-10-29 16:16 UTC
The Trackers API is not accesible in generated bindings for python (I'm using python3).

**Comment by berak** [comment] 2015-10-30 10:02
yes, that's true, before we can do that, some issues have to get solved:

* `cv::Rect2d` has to get wrapped into python (cv2.cpp in main trunk)
* there is no `cv::tracking` namespace in this module, so e.g. `Tracker_create()` will go into the 'global' cv2 namespace. not a bug, but definitely ugly.
* at the bottom of tracker.hpp, there are some `selectROI` exposed to python, even if `Rect2d` works, the `std::string` is problematic (maybe should get changed to cv::String)

**Comment by berak** [comment] 2015-10-30 10:46
you might want to help, and try the Rect2d branch in main, and an early , [experimental branch](https://github.com/berak/opencv_contrib/tree/python_tracking) for the tracking module.

**Comment by WestFlame** [comment] 2015-10-30 10:58
Thank you for such fast response :). I will definitely try it.

**Comment by berak** [comment] 2015-10-30 11:05
just don't forget to setup proper branches for both main & contrib before you merge anything, to keep master clean !

**Comment by berak** [comment] 2015-11-03 07:13
sorry, first attempt was terribly sloppy. can you try again ?

**Comment by WestFlame** [comment] 2015-11-03 14:02
I was finally able to compile and try it. It seems that it works fine. But I've currently tryied only the basic functionality (the `Tracker_create()`, `tracker.init(...)` and `tracker.update(...)` loop).

**Comment by bhack** [comment] 2016-03-03 14:00
Can we close this?

**Closed** 2016-03-03 14:06 UTC
Labels: category: tracking, enhancement
